[package]
name = "sqlx-bootstrap"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1.40"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.sqlx]
version = "0.7.4"
features = ["macros", "postgres", "runtime-tokio-rustls"]
